### ISSUE TITLE
Ширина книжек не постоянная.

### ISSUE THREAD

**Issue by any2djvu** [anaximenes/libtest#3]

**Comment by anaximenes** [comment]
Хмм, в смысле?

**Comment by tau0** [comment]
В прямом, ширина (вернее высота книги не постоянна от книги к книге.

2015-02-01 12:05 GMT+03:00 anaximenes notifications@github.com:

**Comment by anaximenes** [comment]
После стольких изменений, остались на прежнем месте. Мне кажется пусть будет разная высота

![image](https://cloud.githubusercontent.com/assets/8573149/6065198/5c819160-ad74-11e4-970e-e2577a51b805.png)

**Comment by tau0** [comment]
Пусть будет разная, выровнем может быть тумбами:)
